version: '3.7'
services: 
    nginx: 
        build: ./bananat
        container_name: "bananat_angular"
        ports: 
            - "80:80"
        networks: 
            app: 
                ipv4_address: 172.50.1.3
        depends_on:
            - server
    server:
        build: ./server
        container_name: "bananat_server"
        expose: 
            - "4300"
            - "8080"
        ports: 
            - "8080:8080"
        networks: 
            app:
                ipv4_address: 172.50.1.4
        depends_on: 
            - db
    db: 
        image: mongo
        expose: 
            - "27017"
        command: mongod --bind_ip localhost,db
        networks: 
            app: 
                ipv4_address: 172.50.1.5       

networks: 
    app: 
        name: bananat
        ipam:  
            driver: default
            config: 
                - subnet: 172.50.0.0/16